Repository ciemss/pyciemss, pull requests merged in 2023-06, with the labels that each got.

#158 156 create unit test for comparing whether two models have the same deriv function
  notebook/sir_mira_vs_manual.ipynb
  src/pyciemss/utils/__init__.py
  src/pyciemss/utils/petri_utils.py
  test/test_mira/test_petrinet_derivs.py
  test/test_mira/test_regnet_derivs.py
  test/test_petrinet_ode/test_ode.py
Labels: awaiting review

#165 Composed Interfaces and Simple Demo
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/interfaces.py
  src/pyciemss/utils/output_processing_utils.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: awaiting review

#155 153 implement askem model representation for lotka volterra regulatory networks
  notebook/regnet/LotkaVolterra.ipynb
  notebook/regnet/MiraRegnet.ipynb
  notebook/sir_mira_vs_manual.ipynb
  setup.cfg
  src/pyciemss/PetriNetODE/__init__.py
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/PetriNetODE/models.py
  test/models/april_ensemble_demo/BIOMD0000000960_template_model.json
  test/models/askenet_sir.json
  test/models/may-hackathon/lotka_volterra.json
  test/test_mira/test_petrinet_derivs.py
  test/test_mira/test_regnet_derivs.py
  test/test_petrinet_ode/test_ode.py
Labels: awaiting review

#178 Started notebook for examples regarding TA2 issues for model validation
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pyciemss.iml
  .idea/vcs.xml
  notebook/Examples_for_TA2_Model_Representation/Modeling_Representation_Issues_Examples.ipynb
  notebook/Examples_for_TA2_Model_Representation/SEIARHDS_AMR.json
  notebook/Examples_for_TA2_Model_Representation/SEIARHD_AMR.json
  notebook/Examples_for_TA2_Model_Representation/SIRHD_AMR.json
  notebook/Examples_for_TA2_Model_Representation/model.png
  notebook/april_ensemble/synthetic_data_with_custom_models.ipynb
  notebook/sir_mira_vs_manual.ipynb
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/petri_utils.py
Labels: awaiting review

#190 Changes to interfaces to support data IO for TA4
  notebook/integration_demo/data.csv
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: integration

#191 Add detailed docstrings for TA4 interfaces
  src/pyciemss/PetriNetODE/interfaces.py
Labels: integration

#192 Removed untested `add_uncertainty` from TA4 interfaces
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  src/pyciemss/PetriNetODE/interfaces.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: awaiting review, integration

#193 Add parameter interventions to TA4 interfaces
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
  test/test_petrinet_ode/data.csv
  test/test_petrinet_ode/expected_intervened_samples.csv
  test/test_petrinet_ode/test_ode_interfaces.py
  test/test_utils/expected_output_format.csv
Labels: integration
