Repository ciemss/pyciemss, pull requests merged in 2023-12, with the labels that each got.

#427 Scale back number of tests
  tests/fixtures.py
Labels: awaiting review

#424 Parameter Intervention
  pyciemss/compiled_dynamics.py
  pyciemss/interfaces.py
  pyciemss/interruptions.py
  tests/fixtures.py
  tests/test_interfaces.py
  tests/test_interruptions.py
Labels: awaiting response, integration, refactor

#428 Adding regnet urls to fixtures, and limiting number of examples to three per type
  tests/fixtures.py
Labels: awaiting review

#429 Add parameter interventions to calibrate and refactor interface tests
  pyciemss/compiled_dynamics.py
  pyciemss/interfaces.py
  tests/test_interfaces.py
Labels: awaiting review, integration, refactor

#436 bump mira to 0.3.0
  setup.cfg
Labels: awaiting review, integration
