Repository ciemss/pyciemss, pull requests merged in 2023-08, with the labels that each got.

#321 317 odd behavior when plotting data
  notebook/ensemble_eval_sa/ensemble_results/Untitled.ipynb
  notebook/july_evaluation/Vega_Plot_Issue317.ipynb
  src/pyciemss/visuals/trajectories.vg.json
  test/test_visuals/test_schemas.py
Labels: awaiting review

#329 327 some modules no longer import
  src/pyciemss/utils/bilayer_utils.py
  src/pyciemss/utils/synth_data_utils.py
  test/test_modules_import.py
Labels: awaiting review

#346 Create GitHub actions TA4 integration workflow
  .github/workflows/main.yml
Labels: integration

#351 Added unit test for convert_to_output that checks if observables detach tensor
  src/pyciemss/utils/interface_utils.py
  test/models/AMR_examples/ES3_detection_log10V.json
  test/test_utils/test_interface_utils.py
Labels: awaiting review

#354 bumped mira to use the tagged version
  setup.cfg
  src/pyciemss/PetriNetODE/base.py
  test/models/AMR_examples/BIOMD0000000955_askenet.json
  test/models/AMR_examples/ES3_detection_log10V.json
  test/models/AMR_examples/SIDARTHE.amr.json
  test/models/AMR_examples/ensemble/SEIARHDS_AMR.json
  test/models/AMR_examples/ensemble/SIRHD_AMR.json
  test/models/AMR_examples/scenario1_a.json
  test/models/AMR_examples/scenario1_c_with_distributions.json
  test/models/askenet_sir.json
  test/models/may-hackathon/lotka_volterra.json
  test/test_mira/sidarthe_data.csv
  test/test_mira/sir_data.csv
  test/test_mira/test_rate_law.py
  test/test_petrinet_ode/problematic_example/BIOMD0000000955_askenet.json
Labels: integration

#353 Extracted make_quantiles from convert_to_output
  src/pyciemss/utils/interface_utils.py
  test/test_utils/expected_output_quantiles_format.csv
  test/test_utils/test_interface_utils.py
Labels: awaiting review, integration

#364 Vega png export issue
  setup.cfg
  src/pyciemss/visuals/schemas/histogram_static_bins_multi.vg.json
  test/test_visuals/reference_images/multigraph.png
  test/test_visuals/reference_images/multigraph.svg
  test/test_visuals/reference_images/spring_graph.png
  test/test_visuals/reference_images/spring_graph.svg
  test/test_visuals/reference_images/trajectories.png
  test/test_visuals/reference_images/trajectories.svg
  test/test_visuals/test_schemas.py
Labels: bug

#358 Extract posterior densities from inferred parameters at user-specified points
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_quantiles_results.csv
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/quantiles_results.csv
  notebook/integration_demo/results_petri/quantiles_results_w_interventions.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  src/pyciemss/PetriNetODE/interfaces.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: awaiting review, integration
