Repository ciemss/pyciemss, pull requests merged in 2023-07, with the labels that each got.

#194 End-to-end integration of ensemble modeling w/ TA4
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
  test/test_ensemble/test_ensemble_interfaces.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: awaiting review, integration

#203 Vs hackathon prep
  notebook/hackathon_prep/ensemble_challenge.ipynb
Labels: awaiting review

#205 Change setup to fix MIRA name error
  setup.cfg
Labels: bug, awaiting review

#200 Add utilities for loading distributions from AMR
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/utils/distributions.py
  test/test_utils/test_dist/test_mira_to_pyro.py
Labels: awaiting review, integration

#201 Symbolic Rate law to Pytorch Rate law
  notebook/Examples_for_TA2_Model_Representation/Modeling_Representation_Issues_Examples.ipynb
  notebook/Examples_for_TA2_Model_Representation/Symbolic_Deriv_Experiments.ipynb
  notebook/integration_demo/data.csv
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
  setup.cfg
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/__init__.py
  test/models/sir.json
  test/test_ensemble/test_ensemble_interfaces.py
  test/test_mira/test_petrinet_derivs.py
  test/test_mira/test_rate_law.py
  test/test_petrinet_ode/data.csv
  test/test_petrinet_ode/expected_intervened_samples.csv
  test/test_petrinet_ode/test_ode_interfaces.py
  test/test_utils/test_interface_utils.py
Labels: awaiting review

#217 Fix the MIRA version
  setup.cfg
Labels: awaiting review

#227 bump mira
  setup.cfg
  test/test_mira/test_rate_law.py
Labels: bug

#221 Provisional support for time_unit in TA4 interface dataframe
  src/pyciemss/utils/interface_utils.py
  test/test_ensemble/test_ensemble_interfaces.py
  test/test_mira/test_rate_law.py
  test/test_petrinet_ode/test_ode.py
  test/test_petrinet_ode/test_ode_interfaces.py
  test/test_utils/test_interface_utils.py
Labels: awaiting response

#232 Decorator logging function
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/custom_decorators.py
Labels: integration

#204 Optimize interface for TA4 integration
  notebook/december_demo/scenario2.ipynb
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrate_optimize_sample_results.csv
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/optimize_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/risk/ouu.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: enhancement, awaiting review, integration

#235 234 visualization support for trajectory distributions
  .gitignore
  notebook/.gitignore
  notebook/TrajectoryVisualizations.ipynb
  notebook/april_ensemble/demo.ipynb
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri/calibrate_vega.ipynb
  notebook/integration_demo/results_petri/create_polygon.ipynb
  notebook/regnet/LotkaVolterra.ipynb
  notebook/regnet/MiraRegnet.ipynb
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
  src/pyciemss/visuals/barycenter_triangle.vg.json
  src/pyciemss/visuals/calibrate_chart.vg.json
  src/pyciemss/visuals/checks.py
  src/pyciemss/visuals/plots.py
  src/pyciemss/visuals/trajectories.vg.json
  src/pyciemss/visuals/vega.py
  test/data/intervened_samples.json
  test/data/observed_trajectory.json
  test/data/prior_samples.json
  test/test_petrinet_ode/test_ode_interfaces.py
  test/test_visuals/test_checks.py
  test/test_visuals/test_plots.py
  test/test_visuals/test_utils.py
  test/test_visuals/test_vega.py
Labels: awaiting response

#250 change mira version, clean files
  notebook/hackathon_prep/scenario1_constant_beta.json
  notebook/hackathon_prep/scenario1_constant_beta_try_again.json
  setup.cfg
Labels: enhancement, awaiting review

#245 Added pyciemss logging wrapper to optimize endpoint
  src/pyciemss/PetriNetODE/interfaces.py
Labels: documentation, awaiting review

#231 Adding quantiles for ensemble outputs
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri_ensemble/calibrated_quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/utils/interface_utils.py
  test/test_ensemble/test_ensemble_interfaces.py
Labels: awaiting review, integration

#257 Updating definition of pseudocount
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
Labels: awaiting review

#259 Recover demo notebook to add back optimization
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/calibrate_optimize_sample_results.csv
  notebook/integration_demo/results_petri/calibrated_sample_results.csv
  notebook/integration_demo/results_petri/optimize_sample_results.csv
  notebook/integration_demo/results_petri/sample_results.csv
  notebook/integration_demo/results_petri/sample_results_w_interventions.csv
  src/pyciemss/visuals/plots.py
Labels: awaiting review

#247 Scaled Normal Noise Model
  .gitignore
  src/pyciemss/Ensemble/base.py
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/distributions.py
  test/test_ensemble/test_ensemble_interfaces.py
  test/test_petrinet_ode/problematic_example/BIOMD0000000955_askenet.json
  test/test_petrinet_ode/problematic_example/ciemss-dataset-input.csv
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: bug, awaiting review, integration

#258 Scenario1 exploratory
  notebook/hackathon_prep/WY_mapped_data.csv
  notebook/hackathon_prep/scenario1.ipynb
  notebook/hackathon_prep/scenario1_a.json
  notebook/hackathon_prep/scenario1_d.json
Labels: enhancement, awaiting review

#263 Update scenario2.ipynb
  notebook/hackathon_prep/scenario2.ipynb
Labels: enhancement, good first issue, awaiting review

#265 244 calibrate error when using nan entries 1
  src/pyciemss/utils/interface_utils.py
  test/test_utils/test_interface_utils.py
Labels: awaiting review

#260 Removed placeholder parameters from template models when possible
  src/pyciemss/PetriNetODE/base.py
Labels: enhancement, awaiting review

#269 Addressed time collision errors with logging, interventions, and observations
  .gitignore
  src/pyciemss/PetriNetODE/interfaces.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: bug, awaiting review

#271 Update documentation for TA4 interfaces
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/demo_ensemble.ipynb
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  test/test_ensemble/test_ensemble_interfaces.py
  test/test_mira/test_rate_law.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: awaiting review, integration

#277 Bump MIRA to use the most recent version
  setup.cfg
Labels: awaiting review

#278 145 create observation function from amr expression
  notebook/integration_demo/Demonstrate_observables.ipynb
  notebook/integration_demo/sir_data.csv
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
  test/models/AMR_examples/SEIARDH.amr.json
  test/models/AMR_examples/sir_typed.json
  test/test_mira/test_observables.py
  test/test_utils/test_interface_utils.py
Labels: enhancement, awaiting review, integration

#279 Provide an optional list of parameters to be calibrated deterministically
  src/pyciemss/PetriNetODE/interfaces.py
  test/test_petrinet_ode/test_ode_interfaces.py
Labels: enhancement, awaiting review, integration

#280 Extract observables for ensemble modeling
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri_ensemble/calibrated_quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/ensemble_data.csv
  notebook/integration_demo/results_petri_ensemble/quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
  src/pyciemss/Ensemble/base.py
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/base.py
  src/pyciemss/utils/interface_utils.py
  test/models/AMR_examples/ensemble/SEIARHDS_AMR.json
  test/models/AMR_examples/ensemble/SIRHD_AMR.json
  test/models/AMR_examples/ensemble/ensemble_data.csv
  test/test_ensemble/test_ensemble_interfaces.py
Labels: awaiting review, integration

#284 folders for eval
  notebook/july_evaluation/ensemble.ipynb
  notebook/july_evaluation/scenario1.ipynb
  notebook/july_evaluation/scenario2.ipynb
  notebook/july_evaluation/scenario3.ipynb
Labels: enhancement

#292 Moved COVID truth data extraction utils file to correct directory
  src/pyciemss/utils/toronto_ensemble_challenge_utils.py
Labels: awaiting review

#291 Eval 2023/07 Scenario 2
  notebook/hackathon_prep/scenario3_abm.ipynb
  notebook/july_evaluation/Scenario_2a.ipynb
  notebook/july_evaluation/Scenario_2b.ipynb
  notebook/july_evaluation/Scenario_2c.ipynb
Labels: enhancement, awaiting review

#286 Updated all TA4 interfaces to return quantiles
  notebook/integration_demo/demo.ipynb
  notebook/integration_demo/results_petri/sample_results.csv
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/utils/interface_utils.py
Labels: enhancement, WIP, integration

#300 Eval 2023/07 - Ensemble Challenge
  notebook/july_evaluation/Ensemble_1.ipynb
  notebook/july_evaluation/Ensemble_2.ipynb
  notebook/july_evaluation/Ensemble_3.ipynb
Labels: enhancement, awaiting review

#302 Add AMR_utils file to correct utils directory
  src/pyciemss/utils/AMR_utils.py
Labels: enhancement, awaiting review

#272 Scenario 2 - Adding multi-vax/strain models
  notebook/hackathon_prep/scenario2.ipynb
  notebook/hackathon_prep/scenario2_2_b_multi_vax_multi_strain.json
Labels: enhancement, good first issue, awaiting review

#307 Results for ensemble demo notebook with new interface outputs
  notebook/integration_demo/demo_ensemble.ipynb
  notebook/integration_demo/results_petri_ensemble/calibrated_quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/calibrated_sample_results.csv
  notebook/integration_demo/results_petri_ensemble/quantile_results.csv
  notebook/integration_demo/results_petri_ensemble/sample_results.csv
Labels: awaiting review

#308 Log lazily
  src/pyciemss/Ensemble/interfaces.py
  src/pyciemss/PetriNetODE/interfaces.py
  src/pyciemss/custom_decorators.py
Labels: enhancement, awaiting review
