Repository ciemss/pyciemss, pull requests merged in 2024-03, with the labels that each got.

#517 Fix calibrate to work on observables as well as state
  pyciemss/interfaces.py
  pyciemss/observation.py
  tests/test_interfaces.py
Labels: bug, awaiting review

#458 adding testing check_data function to load_data
  pyciemss/integration_utils/observation.py
  tests/fixtures.py
  tests/test_interfaces.py
Labels: awaiting review

#523 Bump mira to 0.5.0
  setup.cfg
Labels: awaiting review

#493 438 add various interventions to interfacesipynb
  .github/workflows/test_notebooks.yml
  docs/source/interfaces.ipynb
  scripts/test_notebooks.sh
Labels: awaiting review

#531 revert removal of notebook test from CI
  .github/workflows/test_notebooks.yml
  docs/source/interfaces.ipynb
Labels: awaiting review

#522 Ensemble calibrate
  pyciemss/interfaces.py
  tests/test_interfaces.py
Labels: enhancement, awaiting review

#533 Add an error if `euler` solver is used without specifying the timesteps.
  docs/source/interfaces.ipynb
  pyciemss/integration_utils/interface_checks.py
  pyciemss/interfaces.py
  tests/integration_utils/test_result_processing.py
  tests/test_interfaces.py
  tests/visuals/test_plots.py
  tests/visuals/test_utils.py
Labels: documentation, awaiting review

#537 adding ensemble calibrate example
  docs/source/interfaces.ipynb
  pyciemss/__init__.py
Labels: awaiting review

#543 Add check if parameters have distributions
  pyciemss/compiled_dynamics.py
  tests/fixtures.py
  tests/test_compiled_dynamics.py
Labels: enhancement, awaiting review

#544 Updated optimize documentation for static_parameter_intervention definition
  pyciemss/interfaces.py
Labels: awaiting review, integration

#549 Add more informative error if adaptive time step underflows
  pyciemss/compiled_dynamics.py
Labels: enhancement, awaiting review

#547 adding INSTALL.md
  INSTALL.md
Labels: awaiting review

#551 add more in-depth README
  README.md
Labels: documentation, awaiting review
