Repository ciemss/pyciemss, pull requests merged in 2024-02, with the labels that each got.

#463 adding labels and calibrate interface example
  docs/source/interfaces.ipynb
Labels: awaiting review

#442 optimize interface refactor
  docs/source/interfaces.ipynb
  pyciemss/__init__.py
  pyciemss/interfaces.py
  pyciemss/ouu/__init__.py
  pyciemss/ouu/ouu.py
  pyciemss/ouu/qoi.py
  pyciemss/ouu/risk_measures.py
  tests/fixtures.py
  tests/test_interfaces.py
Labels: awaiting response, refactor

#450 writing test for calibrate with data mapped to observables
  tests/fixtures.py
  tests/test_interfaces.py
Labels: awaiting review

#473 Block torch gradients for operations that don't require them
  pyciemss/interfaces.py
Labels: enhancement, awaiting review

#471 Add solution mappings to ensemble functionality
  pyciemss/compiled_dynamics.py
  pyciemss/ensemble/compiled_dynamics.py
  pyciemss/integration_utils/result_processing.py
  pyciemss/interfaces.py
  pyciemss/ouu/ouu.py
  tests/fixtures.py
  tests/test_ensemble_compiled_dynamics.py
  tests/test_interfaces.py
Labels: awaiting review, integration, refactor

#486 Pin `pyro==1.8.6` to resolve upstream bugs in ChiRho
  setup.cfg
Labels: awaiting review, upstream

#504 Added risk estimates as an output to results generated from `sample` interface
  docs/source/interfaces.ipynb
  pyciemss/interfaces.py
Labels: awaiting review, feature request

#510 Bump mira to 0.4.0
  setup.cfg
Labels: awaiting review

#512 Updating `optimize` to add intervention builder that can handle optimizing the start time
  docs/source/interfaces.ipynb
  pyciemss/integration_utils/intervention_builder.py
  pyciemss/interfaces.py
  pyciemss/ouu/ouu.py
  tests/fixtures.py
  tests/test_interfaces.py
Labels: enhancement, awaiting review

#511 Add parameter interventions to the trace for downstream reporting
  pyciemss/integration_utils/result_processing.py
  pyciemss/interfaces.py
  pyciemss/interruptions.py
  tests/integration_utils/test_result_processing.py
  tests/test_interfaces.py
Labels: enhancement, awaiting review
