Repository ciemss/pyciemss, pull requests merged in 2024-01, with the labels that each got.

#444 Add back pyciemss logging wrapper to calibrate
  pyciemss/interfaces.py
Labels: awaiting review, integration

#445 Add progress hook (and example usage in test) for `calibrate`
  pyciemss/interfaces.py
  tests/test_interfaces.py
Labels: awaiting review, integration

#446 Add parallel sampling when there are no interventions
  pyciemss/interfaces.py
  pyciemss/mira_integration/compiled_dynamics.py
Labels: awaiting review, integration

#443 Alter and bugfix for service integration
  pyciemss/interfaces.py
  setup.cfg
  tests/test_interfaces.py
Labels: integration

#455 adding check on num_samples
  pyciemss/interfaces.py
  tests/test_ensemble_sample_error_messages.py
  tests/test_sample_error_message.py
Labels: awaiting review

#457 adding check for num_iterations in calibrate
  pyciemss/interfaces.py
  tests/test_calibrate_error_messages.py
Labels: awaiting review

#465 Removing `unittest` in favor of `pytest`
  tests/fixtures.py
  tests/test_calibrate_error_messages.py
  tests/test_ensemble_sample_error_messages.py
  tests/test_interfaces.py
  tests/test_sample_error_message.py
Labels: awaiting review
