Repository ciemss/pyciemss, pull requests merged in 2024-04, with the labels that each got.

#564 Simplify interchange dictionary processing
  pyciemss/integration_utils/result_processing.py
  tests/integration_utils/test_result_processing.py
Labels: awaiting review, refactor

#573 Resolved misalignment between `sample` and visualization tests
  tests/visuals/test_plots.py
Labels: awaiting review, testing

#570 Adding support for ensemble output format
  docs/source/interfaces.ipynb
  pyciemss/integration_utils/result_processing.py
  pyciemss/interfaces.py
  tests/fixtures.py
  tests/test_interfaces.py
  tests/visuals/test_plots.py
  tests/visuals/test_utils.py
Labels: awaiting review, integration
