Repository ciemss/pyciemss, pull requests merged in 2024-08, with the labels that each got.

#597 Allow for interventions on constant parameters
  pyciemss/compiled_dynamics.py
  tests/fixtures.py
  tests/test_interfaces.py
Labels: bug, awaiting review

#596 Updating `optimize` to handle multiple risk constraints
  docs/source/interfaces.ipynb
  docs/source/optimize_interface.ipynb
  pyciemss/integration_utils/intervention_builder.py
  pyciemss/interfaces.py
  pyciemss/mira_integration/distributions.py
  pyciemss/ouu/ouu.py
  pyciemss/ouu/qoi.py
  tests/fixtures.py
  tests/test_interfaces.py
Labels: enhancement, awaiting review, integration

#602 changing interfaces line 535 to include observables
  pyciemss/interfaces.py
Labels: awaiting review

#592 477 add progress hook to optimize
  docs/source/interfaces.ipynb
  pyciemss/interfaces.py
  pyciemss/ouu/ouu.py
  tests/test_interfaces.py
Labels: enhancement, awaiting review

#603 Bump Mira dependency to 0.7.0
  setup.cfg
Labels: awaiting review

#605 added schema.vg.json and heatmap/ to gitignore
  .gitignore
Labels: awaiting review
